### PR TITLE
realease binary

### PR DESCRIPTION
**Pull request by sosan**
github action release binary

### CODE REVIEW

**Comment by compnerd** [comment]
Hi, thanks for the suggestion here.  Would you mind splitting up the work into two separate things - one of them is improving the documentation, which I really do appreciate.

The second is for the release binaries.  I think that the release binary idea is very cool, but I would prefer that it requires a specific action to trigger that job - like tagging a release should trigger that job and upload the binary.

**Comment by sosan** [comment]
added release conditional with [release] message

**Comment by compnerd** [comment]
Oh, that is a really cool trick for the release management!   Thank you so much for that!  I'm actually hoping to cut a 0.0.1 release soon since I think I just figured out the last bit of the changes that I wanted to do for one of the dependencies.

**Comment by compnerd** [comment]
@sosan oh, one thing that would be really useful is to do that particular build with `-c release` so that the release is actually done with the release mode optimizations.

**Comment by sosan** [comment]
done :) btw else: dont exist on github actions :/ so bit tricky
edited: https://github.com/sosan/swift-devenv/blob/master/.github/workflows/swift.yml

**Comment by compnerd** [comment]
Ah, I actually found that GitHub has something for this already?  It showed how to trigger the task on the tag.  I'm not very familiar with the GitHub Actions, so if you have a better way to do that than splitting it up into two different workflows, it would be great, but, seems like something like #8 might be a good thing to allow triggering the release only on tagging of a release rather than requiring a commit.

**Pull request merged**
